arcoiris=("Azul","Verde","Rojo","amarillo")
print(arcoiris)
print("-longitd arcoiris--")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print("elementos de la tupla")
print(animales[1])
rateros=("juan","ana", "pedro")
y = list(rateros)
y[0] = "polainas"
x = tuple(y)
print(x)
print("agregamdo elementos")
Nanimal=("boby","chetos")
y = list(Nanimal)
print(y)
y.append("tontolin")
otratupla = tuple(y)
print(otratupla)
print("uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)